name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 2.7
            plone-version: 43
          - python-version: 2.7
            plone-version: 50
          - python-version: 2.7
            plone-version: 51
          - python-version: 3.7
            plone-version: 52
          - python-version: 3.8
            plone-version: 52
    steps:
      # git checkout
      - uses: actions/checkout@v2

      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # python cache
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # python install
      - name: pip install
        run: pip install -r requirements.txt

      # buildout
      - name: buildout
        run: buildout -t 10 -c test_plone${{ matrix.plone-version }}.cfg

      # test
      - name: test
        run: bin/test
